#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#site routes
homepage:
  path: /
  controller: App\Controller\HomeController::Index

dashboard.messages:
  path: /dashboard/messages
  controller: App\Controller\DshMessageController::Index